plan_fairytale:
  description: >
    Create a plan for a fairytale with given inputs 
    Character name: {character_name}
    Location: {location}
    Main problem: {main_problem}

    If following input is not empty: "{inspiration_book}" you shold:
     - query table `kbc-euw3-2179-8b66`.`out_c_mysql_fairytales_cleaned`.`clean_book_summaries`
     - use summary of book for inspiration
     - add summary of book to the plan
     - make extra sure you will make maximum effort to query the table if input is not empty
     - - if you are unable to query the table, say so and continue with the plan

     
  expected_output: >
    A plan for a fairytale. Do not write the story, only plan it.
    Last line should be summary of book used for inspiration.
  agent: fairytale_planner

write_fairytale:
  description: >
    Write a fairytale with given inputs {story_plan}
  expected_output: >
    A fairytale story. Do not plan the story, only write it.
  agent: fairytale_writer


translate_fairytale:
  description: >
    Translate the fairytale story to given language: {target_language}
  expected_output: >
    A fairytale story in given language. Use markdown format and keep the story as it is.
  agent: fairytale_translator